# Generated by Django 2.1.7 on 2019-05-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producto', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('clave_producto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
